const assert = require('assert/strict')
const fs = require('fs'), os = require('os'), path = require('path')
const {spawnSync} = require('child_process')
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'omarchyform-files-'))
try {
  const boards=path.join(dir,'boards'),trash=path.join(dir,'trash'),outside=path.join(dir,'outside')
  for (const d of [boards,trash,outside]) fs.mkdirSync(d)
  const run=(...args)=>spawnSync('bash',[path.join(__dirname,'../BoardFiles.sh'),...args],{encoding:'utf8'})
  fs.writeFileSync(path.join(trash,'old'),'old')
  fs.writeFileSync(path.join(boards,'a.json'),'new')
  assert.notEqual(run('move',trash,'old',boards,'a.json').status,0)
  assert.equal(fs.readFileSync(path.join(trash,'old'),'utf8'),'old')
  fs.mkdirSync(path.join(boards,'folder'))
  fs.mkdirSync(path.join(trash,'folder'))
  assert.notEqual(run('move',trash,'folder',boards,'folder').status,0)
  assert.equal(fs.existsSync(path.join(boards,'folder/folder')),false)
  assert.equal(run('move',trash,'old',boards,'nested/restored.json').status,0)
  assert.equal(fs.readFileSync(path.join(boards,'nested/restored.json'),'utf8'),'old')
  fs.symlinkSync(outside,path.join(boards,'escape'))
  fs.writeFileSync(path.join(trash,'another'),'keep')
  assert.notEqual(run('move',trash,'another',boards,'bad\nname.json').status,0)
  assert.notEqual(run('move',trash,'another',boards,'escape/board.json').status,0)
  assert.notEqual(run('purge',trash,'../boards').status,0)
  fs.symlinkSync(boards,path.join(trash,'link'))
  assert.notEqual(run('purge',trash,'link').status,0)
  assert.equal(run('backup',path.join(boards,'escape/a.json'),path.join(trash,'backup'),boards).status,3)
  assert.equal(fs.existsSync(path.join(boards,'a.json')),true)
  assert.equal(run('check',boards,'escape/a.json').status,3)
  assert.equal(run('check',boards,'a.json').status,0)
  assert.equal(run('check',boards,'not-yet/new.json').status,0)
  // A symlinked root is where the user keeps their data, not an escape.
  const linkedBoards=path.join(dir,'linked-boards'),linkedBackups=path.join(dir,'linked-backups')
  fs.mkdirSync(path.join(dir,'backups'))
  fs.symlinkSync(boards,linkedBoards)
  fs.symlinkSync(path.join(dir,'backups'),linkedBackups)
  assert.equal(run('backup',path.join(linkedBoards,'a.json'),path.join(linkedBackups,'a.json.bak'),linkedBoards,linkedBackups).status,0)
  assert.equal(fs.readFileSync(path.join(dir,'backups/a.json.bak'),'utf8'),'new')
  assert.equal(run('purge',trash,'another').status,0)
} finally {fs.rmSync(dir,{recursive:true,force:true})}
console.log('ok — filesystem confinement and restore collisions')
